---
# tasks file for hadoop_master
          - stat:
                  path: /home/ec2-user/jdk-8u171-linux-x64.rpm
            register: x
          - stat:
                  path: /home/ec2-user/hadoop-1.2.1-1.x86_64.rpm
            register: y

          - name: copying jdk software
            copy:
                  dest:  /home/ec2-user/
                  src:  /root/jdk-8u171-linux-x64.rpm
            when:  x.stat.exists!=True

          - name: copying the hadoop software
            copy:
                  dest: /home/ec2-user
                  src: /root/hadoop-1.2.1-1.x86_64.rpm
            when:  y.stat.exists!=True
          - block:
                  - name: installing jdk
                    shell: "sudo rpm -i jdk-8u171-linux-x64.rpm"
                    register: jdk_info
            rescue:
                    - debug:
                            var: jdk_info
          - block:
                  - name: installing hadoop
                    shell: "sudo rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
                    register: hadoop_info
            rescue:
                    - debug:
                            var: hadoop_info



          - name: configuring the mapred files
            blockinfile:
                    path: /etc/hadoop/mapred-site.xml
                    insertafter: "<configuration>"
                    block: |
                            <property>
                            <name>mapred.job.tracker</name>
                            <value>0.0.0.0:9002</value>
                            </property>

          - block:  
             - name: starting the jobtracker
               shell: "sudo hadoop-daemon.sh start jobtracker"
               register: check_info
            rescue:
                    - debug:
                            var: check_info   

