---
# tasks file for hadoop_master
          - stat:
                  path: /home/ec2-user/jdk-8u171-linux-x64.rpm
            register: x
          - stat:
                  path: /home/ec2-user/hadoop-1.2.1-1.x86_64.rpm
            register: y

          - name: copying jdk software
            copy:
                  dest:  /home/ec2-user/
                  src:  /root/jdk-8u171-linux-x64.rpm
            when:  x.stat.exists!=True

          - name: copying the hadoop software
            copy:
                  dest: /home/ec2-user
                  src: /root/hadoop-1.2.1-1.x86_64.rpm
            when:  y.stat.exists!=True
          - block:
                  - name: installing jdk
                    shell: "sudo rpm -i jdk-8u171-linux-x64.rpm"
                    register: jdk_info
            rescue:
                    - debug:
                            var: jdk_info
          - block:
                  - name: installing hadoop
                    shell: "sudo rpm -i hadoop-1.2.1-1.x86_64.rpm --force"
                    register: hadoop_info
            rescue:
                    - debug:
                            var: hadoop_info

          - name: creating directories
            file:
                    path: /dn
                    state: directory

          - name: transferring the hdfs files
            blockinfile:
                    path: /etc/hadoop/hdfs-site.xml
                    insertafter: "<configuration>"
                    block: |
                            <property>
                            <name>dfs.data.dir.</name>
                            <value>/dn</value>
                            </property>


          - name: transferring the core files
            blockinfile:
                    path: /etc/hadoop/core-site.xml
                    insertafter: "<configuration>"
                    block: |
                            <property>
                            <name>fs.default.name</name>
                            <value>hdfs://{{ groups['tag_name_hadoop_master'][0] }}:9001</value>
                            </property>

                    
           
          - block:  
             - name: starting the datanodes
               shell: "sudo hadoop-daemon.sh start datanode"
               register: check_info
            rescue:
                    - debug:
                            var: check_info   

